### ISSUE TITLE
[FEATURE] Update gas estimate in storage check

### ISSUE THREAD

**Issue by tombeckenham** [onflow/FRW-Extension#266]
### Issue to be solved

The amount of gas estimated needs to be updated as reported by @lmcmz 

### Suggest A Solution

Update one line above:
From
let averageTxFee = 0.001
to
let averageTxFee = freeGasEnable ? 0 : 0.0005

**Comment by Peppermint1020** [comment]
@tombeckenham 

(1) This issue fixed when transfer other fts, but still reproduced when transfer NFTS.
We need to make sure when user turn on free gas fee, transfer NFTS to other flow account or child account(dapper wallet) not trigger storage alert.

The process video attached:
https://github.com/user-attachments/assets/56b0f606-23b4-4c5f-8736-63050879a924

(2) Another issue I find in this build is when I failed to move ft tokens, the storage alert not pop up.
tx id:https://www.flowscan.io/tx/e3ebaea2f37b4ec5666967003c0070846bc79851b2f8364ab467f6e4005412ef
The process video attached:
https://github.com/user-attachments/assets/8f061f89-0ffc-43bf-8bac-d50a423ad482

**Comment by Peppermint1020** [comment]
When user have 0.001 token/minimum storage required token amount in flow wallet， and turn on free gas fee
We need show storage alert notification

- [x] （1）move flow token to evm
- [x] （2） move other ft to evm
- [x] （3） move nft to evm
- [ ] （4）move flow token from evm to flow 【question】
![Image](https://github.com/user-attachments/assets/99f649c1-9472-4055-a3aa-812f95fb8602)

- [x] （5）move other ft token from evm to flow
- [ ] （6） move nft from evm to flow
![Image](https://github.com/user-attachments/assets/987eae6b-7979-4027-a70d-d69e1d47a40b)
- [ ] （7） send flow token to evm
![Image](https://github.com/user-attachments/assets/cac8638d-5fcf-4ba7-be3d-c5d063b98e7d)
- [ ] （8） send other ft to evm
![Image](https://github.com/user-attachments/assets/64f20a42-987e-4a82-be3a-061668f0223e)

- [x] （9） send nft to evm
- [ ] （10）send flow token from evm to flow 【question】
- [ ] （11）send other ft token from evm to flow
![Image](https://github.com/user-attachments/assets/a57d565e-ccf7-4eb0-ba7a-73576e9513e5)
- [ ] （12）send nft from evm to flow
![Image](https://github.com/user-attachments/assets/97c6b36b-229c-4730-98b8-47d6dd9e829e)
- [ ]   (13)   send flow token from Flow to EOA
![Image](https://github.com/user-attachments/assets/95c136e1-691e-49c3-9e67-295f541af6d5
- [ ]   (14)   send other ft from Flow to EOA
- [ ]    (15) send NFT from flow to EOA
- [ ]  (16) send/move flow token from flow to child account
![Image](https://github.com/user-attachments/assets/8a99bbed-e28d-45c0-938e-60175a9a900a)

- [ ]  (17) send lower than 0.001 flow token from flow to other flow [Edge case]

We shouldn’t show storage alert notification

- [x] (1) send ft from flow to flow
- [x] (2) send nft from flow to Flow
- [x] (3) send/move nft from flow to child account

Issues:
(1) No storage alert pop up when failed to transfer due to storage reason. Error 1103: https://www.flowscan.io/tx/17b55632fa8a5b61d4795c0dd7f8111c7db52dd751188ca4454ca0c4a077fc39

Questions:
(1) If we move/send FLOW token from evm to flow, should we show alert? Because actually after the action, user will have more token in their flow account.

**Comment by tombeckenham** [comment]
Yesterday we agreed to limit the scope of the storage alert feature. A feature flag is being added around the 'transaction prediction' code as it is extremely complex to implement. The new feature flag will be in the remote config and be called `tx_warning_prediction`. If this is true then "Show transaction warning prediction including insufficient storage/balance to user". It will be false for now
