### ISSUE TITLE
[Event Tracking] Add mixpanel event tracking

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-Extension#94]
https://app.gitbook.com/o/btnrCjBfFA1CijnAHf9d/s/uD5IIQEzBNOcwceEz9qr/

**Comment by tombeckenham** [comment]
List of events and items to do:

- [x] super_events
- [x] Identify User
- [x] script_error
- [x] delegation_created
- [x] on_ramp_clicked
- [x] coa_creation
- [ ] security_tool
- [x] multi_backup_created
- [x] multi_backup_creation_failed
- [ ] cadence_transaction_signed
- [ ] evm_transaction_signed
- [x] ft_transfer
- [x] nft_transfer
- [x] Transaction Result
- [x] account_created
- [x] account_creation_time (time it takes to create an account)
- [ ] account_recovered

**Comment by tombeckenham** [comment]
I've had a look at the Mixpanel documentation to remember how security works and whether we'll have issues with tracking in the chrome extension. In short, yes we will:

1. The project token is not secret - it can be used and embedded freely and it is not locked to any domain. This is the way Mixpanel was designed. This does mean that anyone can access that project token and use it to send data to our Mixpanel. But why would they... ?
2. However, mixpanel-browser front end SDK can only be used in the popup. It cannot be called from the service worker. This is because the SDK requires access to the window object - which service workers can't get to. There is no option for service workers besides creating a backend proxy service
3. If I do move all the tracking to the popup, we'll get issues with ad blockers. Mixpanel's documentation suggests that up to 30% of all events will be lost. With our user base, potentially that number will be higher. I'm wondering, however, if that would be a good thing? It would give our users a way to disable mixpanel tracking if they want to stay anonymous. If we move tracking to the backend, we'd need to create a feature to disable it and include code to disable it

My recommendation is that I implement Mixpanel tracking on the front end.

- Our users can block tracking using standard means if they want to
- It's less complicated to implement. I won't have to create a backend, or batch api calls etc
- It'll give us "some information" quickly

I'm also thinking that maybe we want to put in some sort of transaction analytics that reads the flow blockchain and sends information to mixpanel. That would be a better "backend" way to track what users are doing.

**Comment by Peppermint1020** [comment]
List of events and items to do:


- [ ] super_events
- [ ] Identify User
- [ ] script_error
- [ ] delegation_created
- [ ] on_ramp_clicked
- [ ] coa_creation
- [ ] security_tool: not applied on extension
- [ ] multi_backup_created: not applied on extension
- [ ] multi_backup_creation_failed: not applied on extension
- [ ] cadence_transaction_signed
- [ ] evm_transaction_signed
- [ ] ft_transfer
- [ ] nft_transfer
- [ ] Transaction Result
- [ ] account_created
- [ ] account_creation_time (time it takes to create an account)
- [ ] account_recovered

**Comment by Peppermint1020** [comment]
Tested on https://github.com/Outblock/FRW-Extension/actions/runs/12092593566
(1) All event names are currently displayed as "page view"; they should display the event names from the GitBook events.
![Image](https://github.com/user-attachments/assets/caf30a55-019d-4478-95a7-99cd43d01cfd)
Expectation behaviour is:
![Image](https://github.com/user-attachments/assets/40e6a8a6-fcec-42f4-9bad-0407146a729c)

(2)We have Production Mixpanel project Id. Please spilt our DEV and Production ENV accordingly.

**Comment by Peppermint1020** [comment]
@tombeckenham 
Please check following issues.
Tested on https://github.com/Outblock/FRW-Extension/actions/runs/12345848657

- [ ] super_events
<img width="1371" alt="Image" src="https://github.com/user-attachments/assets/c3d0c514-0b4a-4518-a92d-16d9f2b22f46" />
We need include following keys for all events
<img width="993" alt="Image" src="https://github.com/user-attachments/assets/08d6635b-ccb1-4d01-b21a-174b7ee327ed" />

- [x] Identify User
<img width="922" alt="Image" src="https://github.com/user-attachments/assets/4192eaff-71d4-4986-923d-c367b622ebb8" />

- [x] script_error:This event has not been triggered as not meet script error.
- [x] delegation_created
<img width="1361" alt="Image" src="https://github.com/user-attachments/assets/7a95a465-fceb-414c-a45e-1df8c6d72047" />

- [x] on_ramp_clicked
<img width="1399" alt="Image" src="https://github.com/user-attachments/assets/b5a3f08c-9e2a-4c6c-bb32-1e00420f7667" />

- [ ] coa_creation
This event has not been triggered when I create COA account for previous account. https://www.flowscan.io/tx/6f4cf74ae0866cdb0097d526b7ba88d7e9a84e07b0df49ecd17ff91bab18d508
- [ ] cadence_transaction_signed
This event has not been triggered when send ft/nft from flow to other flow address.
- [ ] evm_transaction_signed
This event has not been triggered when have evm transaction
- [ ] ft_transfer
<img width="1194" alt="Image" src="https://github.com/user-attachments/assets/99ff3a9f-90b0-4577-a23d-661853bd0566" />
The value of type is type of FT send and ft_identifier should in following format
<img width="595" alt="Image" src="https://github.com/user-attachments/assets/5d91de41-2330-42b3-8307-165d78c197b5" />

- [ ] nft_transfer
<img width="1191" alt="Image" src="https://github.com/user-attachments/assets/6b66f063-7332-4964-824f-1f7ef0e03ed0" />
 The nft_identifier should in following format.
<img width="855" alt="Image" src="https://github.com/user-attachments/assets/10f7df38-1980-44c3-aba1-1957c800dc2d" />


- [ ] Transaction Result
This event has not been triggered.
- [ ] account_created
<img width="1192" alt="Image" src="https://github.com/user-attachments/assets/351aa308-11c9-4781-b73a-5e992e77bc02" />
We miss key_type.
<img width="801" alt="Image" src="https://github.com/user-attachments/assets/8e4d1b9d-eb92-48f6-948a-3e24db10316b" />

- [ ] account_creation_time (time it takes to create an account)
This event has not been triggered
- [ ] account_recovered
The "method" field is empty.
<img width="1188" alt="Image" src="https://github.com/user-attachments/assets/bfb9a06d-b5e7-4788-8bdb-f66dc5cde64e" />

**Comment by Peppermint1020** [comment]
Confirm with Tom.
The issue is the MixPanel transaction tracking code is repeated across dozens of components that we are planning to refactor.
We decide to go with what we have with MixPanel then update it later
